# Generated by Django 4.2.2 on 2023-06-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_blogmodel_blog_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commented_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
