# Generated by Django 4.2.2 on 2023-06-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_delete_commentmodel_alter_blogmodel_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('commented_at', models.DateTimeField(auto_now=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_app.blogmodel')),
            ],
        ),
    ]
